Iter9
Arti9991/shortener pull request #9
Opened 2024-12-19 13:25 UTC by Arti9991

2024-12-22 22:14 UTC, avhitrov requested changes
В основном все ок, но необходимо более компетентно обрабатывать ошибки. Везде, где они возникают и их невозможно игнорировать, необходимо выходить с передачей ошибки наверх.
При указании имени файла `-f=""` (пустышка) необходимо откатываться на in-memory модель и не спамить в логи. При инициализации хранилища, помимо проверки на пустое значение, необходимо также проверять, можно ли работать с переданным значением FILE_STORAGE_PATH (проверить наличие и попытаться открыть на Read-Write).

2024-12-22 22:14 UTC, avhitrov commented on internal/files/files.go
> +func (d *FileData) FileRead() {
```suggestion
func (d *FileData) FileRead() error {
```
1. Функция должна транслировать наверх возникшие ошибки
2. Нет смысла делать операции с файлом, если мы, например, не смогли его открыть

2024-12-22 22:14 UTC, avhitrov commented on internal/files/files.go
> +func NewFiles(path string, stor *storage.Data) *FileData {
```suggestion
func NewFiles(path string, stor *storage.Data) (*FileData, error) {
```
Нужны, как минимум проверки на имя и доступность файла. Возможно, на возможность его создания. В настоящий момент если указать `-f=""` будет постоянная ругань в логах на невозможность работы с файлом.
В этом случае правильный паттерн - вообще откатиться на in-memory хранилище.

2024-12-22 22:14 UTC, avhitrov commented on internal/files/files.go
> +		logger.Log.Info("Error in creating file!", zap.Error(err))
```suggestion
		logger.Log.Info("Error in creating file!", zap.Error(err))
		return err
```

2024-12-22 22:14 UTC, avhitrov commented on internal/files/files.go
> +func (d *FileData) FileSave(key string, val string) {
```suggestion
func (d *FileData) FileSave(key string, val string) error {
```

2024-12-22 22:14 UTC, avhitrov commented on internal/files/files.go
> +		logger.Log.Info("Error in creating file!", zap.Error(err))
```suggestion
		logger.Log.Info("Error in creating file!", zap.Error(err))
		return err
```

2024-12-23 17:55 UTC, Arti9991 commented on internal/files/files.go
> +func NewFiles(path string, stor *storage.Data) *FileData {
Обновил функцию инициализации. Добавил проброс ошибки для нее на верхний уровень. Также добавил флаг "inMemory" в структуру. При инициализации пробую открыть файл на чтение-запись, если ошибка (или путь пустой), то флаг ставится true и программа работает только с временной памятью

2024-12-23 17:56 UTC, Arti9991 commented on internal/files/files.go
> +		logger.Log.Info("Error in creating file!", zap.Error(err))
Добавил вывод ошибок уровень

2024-12-25 20:11 UTC, avhitrov approved these changes
Замечания отработаны и довольно качественно. Аппрув!

2024-12-26 12:38 UTC, merged